In [5]:
import pandas as pd
import numpy as np

In [3]:
scada = pd.read_csv('./train_val.csv')
scada.head(5)

,Unnamed: 0,Date/Time,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (째),speed_cos,speed_sin
0,0,01 01 2018 00:00,380.047791,5.311336,416.328908,259.994904,-0.922769,-5.230563
1,1,01 01 2018 00:10,453.769196,5.672167,519.917511,268.641113,-0.134514,-5.670572
2,2,01 01 2018 00:20,306.376587,5.216037,390.900016,272.564789,0.233413,-5.210812
3,3,01 01 2018 00:30,419.645905,5.659674,516.127569,271.258087,0.124264,-5.658310
4,4,01 01 2018 00:40,380.650696,5.577941,491.702972,265.674286,-0.420723,-5.562052

In [12]:
scada['speed_cos'] = scada['Wind Speed (m/s)'] * np.cos(scada['Wind Direction (째)']*(2 * np.pi)/360)
scada['speed_sin'] = scada['Wind Speed (m/s)'] * np.sin(scada['Wind Direction (째)']*(2 * np.pi)/360)

In [14]:
scada.to_csv('./train_val.csv')

In [5]:
train_val = scada
speed_cos = train_val['speed_cos']
speed_sin = train_val['speed_sin']
power_curve = train_val['Theoretical_Power_Curve (KWh)']
active_power = train_val['LV ActivePower (kW)']

In [7]:
speed_cos.to_numpy()

array([-0.92276908, -0.13451444,  0.23341275, ...,  0.77294842,
        0.93606923,  1.34147311])

In [7]:
kdd = pd.read_csv('../kdd/sdwpf134_initial_kddcup.csv')

In [8]:
kdd.head(10)

,TurbID,Day,Tmstamp,Wspd,Wdir,Etmp,Itmp,Ndir,Pab1,Pab2,Pab3,Prtv,Patv
0,1,1,00:00,2.81,-2.00,16.61,30.95,148.0,0.03,0.03,0.03,-19.38,111.13
1,1,1,00:15,2.48,-4.30,16.38,30.83,148.0,0.03,0.03,0.03,-15.69,75.30
2,1,1,00:30,1.16,9.28,16.62,31.05,135.0,0.03,0.03,0.03,-2.50,9.54
3,1,1,00:45,0.92,14.38,16.13,31.20,148.0,0.04,0.04,0.03,-0.70,0.00
4,1,1,01:00,1.38,-4.28,15.12,29.52,148.0,89.68,89.69,89.50,-0.30,0.00
5,1,1,01:15,2.47,53.36,14.94,29.75,148.0,89.68,89.69,89.50,-0.30,0.00
6,1,1,01:30,1.54,65.50,14.81,29.85,148.0,89.68,89.69,89.50,-0.30,0.00
7,1,1,01:45,3.48,80.50,15.06,29.67,148.0,89.68,89.69,89.50,-0.30,0.00
8,1,1,02:00,1.97,-5.88,16.75,30.08,228.0,7.97,7.97,7.96,-0.30,0.00
9,1,1,02:15,3.36,3.70,17.63,30.52,217.0,0.01,0.01,0.01,-24.00,108.44

KeyError: 'key of type tuple not found and not a MultiIndex'

In [15]:
for j in range(kdd.shape[0]):
    kdd.iloc[j]['Tmstamp'] =

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_28888/1037735060.py, line 2)